name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up both Python and Node.js first
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/frontend/package-lock.json
      
      # Frontend build must happen before backend tests
      - name: Install frontend dependencies
        working-directory: app/frontend
        run: npm ci
      
      - name: Build frontend
        working-directory: app/frontend
        run: npm run build
        
      # Now run backend tests (which depend on frontend build)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/backend/requirements.txt
          
      - name: Run Python tests
        run: |
          python -m pytest app/backend/tests/ -v
      
      # Finally run frontend tests
      - name: Run frontend tests
        working-directory: app/frontend
        run: npm test
